### ISSUE TITLE
Download problem data & meta data

### ISSUE THREAD

**Issue by rambasnet** [rambasnet/kattis-cli#1]
- [ ] Download problem sample data and store them into the **data** folder
- [ ] Download metadata on problem - CPU time, Memory, etc.
- [ ] Store metadata using yaml to avoid multiple requests
