### ISSUE TITLE
Show problem meta data

### ISSUE THREAD

**Issue by rambasnet** [rambasnet/kattis-cli#3]
- [x] Provide an argument to display the metadata on the problem
- [x] CPU Time Limit, Memory Limit, Difficulty, My Submissions, Source
- [ ] Statistics - Top 10? May be not a priority
